# Generated by Django 2.0.5 on 2018-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
