# Generated by Django 2.0.5 on 2018-05-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0003_auto_20180515_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='shopper',
        ),
        migrations.DeleteModel(
            name='Shopper',
        ),
    ]
