# Generated by Django 2.0.5 on 2018-05-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0004_auto_20180515_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppers.Store'),
        ),
    ]
