# Generated by Django 2.0.5 on 2018-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0007_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
