# Generated by Django 2.0.5 on 2018-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180509_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.CharField(default='Subject', max_length=255),
            preserve_default=False,
        ),
    ]
